name: "Create Tags"

on:
  # Start only after Build was finished
  workflow_run:
    workflows: [Build]
    branches: [main]
    types: [completed]

jobs:
  check-hsmcpp-version:
    runs-on: ubuntu-latest
    outputs:
      commit_version: ${{ steps.get_version.outputs.commit_version }}
      commit_action: ${{ steps.get_version.outputs.commit_action }}

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/get-commit-version
        id: get_version
        with:
          repo_dir: ${{ env.GITHUB_WORKSPACE }}
          commit_sha: ${{ github.event.workflow_run.head_sha }}

  deploy-platformio-arduino:
    runs-on: ubuntu-latest
    needs: check-hsmcpp-version

    # only run for successful build after push event
    # avoid running this action on forks
    if: ${{ (github.repository == 'igor-krechetov/hsmcpp') && (needs.check-hsmcpp-version.outputs.commit_version != '') && (needs.check-hsmcpp-version.outputs.commit_action == '[r]') && ((github.event.workflow_run == null) || ((github.event.workflow_run.conclusion == 'success') && (github.event.workflow_run.event == 'push'))) }}

    steps:
      # need to checkout current repo because workflow is not related with push event
      - uses: actions/checkout@v3

      # prepare gpg for sommit signing
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: ${{github.workspace}}

      - name: Commit new files
        run: |
          git tag ${{needs.check-hsmcpp-version.outputs.commit_version}} ${{ github.event.workflow_run.head_sha }}
          git push origin ${{needs.check-hsmcpp-version.outputs.commit_version}}

